name: Build and push Oracle JDK Docker image

on:
  push:
    branches:
      - "main"
permissions:
  id-token: write
  contents: read

jobs:
  build_maven_3_5_2_jdk8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::601238391153:role/karibulabs-github-actions-sofware-role
          role-session-name: github-actions-maven-3_5_2-jdk8-session
          aws-region: us-east-1
      - name: Download Maven 3.5.2 and Corretto JDK 8 from S3
        run: |
          aws s3 cp s3://karibu-software/amazon-corretto-8.472.08.1-linux-x64.tar.gz ./3.5.2-jdk8/amazon-corretto-8.472.08.1-linux-x64.tar.gz
          aws s3 cp s3://karibu-software/apache-maven-3.5.2-bin.tar.gz ./3.5.2-jdk8/apache-maven-3.5.2-bin.tar.gz
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Maven 3.5.2 with JDK 8
        uses: docker/build-push-action@v5
        with:
          context: ./3.5.2-jdk8
          file: ./3.5.2-jdk8/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/maven:3.5.2-jdk8